### ISSUE TITLE
Unable to edit commit in Mac

### ISSUE THREAD

**Issue by dotansimha** [Urigo/tortilla#23]
Started with:
`tortilla edit step "21.10"`

Then edited the file, and typed: `git commit --amend`, got the errors:
```
Dotans-MacBook-Pro:meteor-angular2.0-socially dotansimha$ git commit --amend package.json 
/usr/local/lib/node_modules/tortilla/src/hooks/pre-commit.js:13
  if (!Git.gonnaAmend()) throw Error(
                         ^

Error: New commits are prohibited! Use `$ npm step -- push` instead
    at Error (native)
    at /usr/local/lib/node_modules/tortilla/src/hooks/pre-commit.js:13:32
    at Object.<anonymous> (/usr/local/lib/node_modules/tortilla/src/hooks/pre-commit.js:58:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

Had to override using `--no-verify` and then `git rebase --continue`

**Comment by srtucker22** [comment]
I'm getting this issue but with git version 2.11. I think it should really work regardless of git version in order not to confuse ppl since this seems like a core step in my process.

Maybe my process is a bit off too, but so far it's been:
1. `tortilla create`
2. add stuff to my project
3. `tortilla step push -m 'stuff' (by the way, if you don't add a message, you break the whole system!)
4. repeat steps 2,3 till sub-steps are complete
5. `tortilla step tag -m 'better make a commit msg or things will break'`
6. `tortilla manual render --all` get the manual files created
7. `tortilla step edit` edit the manual
8. `tortilla manual render step X` rerender the manual
9. `git commit --amend` apply the changes
10. `git rebase --continue` finish editing major step and move to next step
11. repeat steps 2-10

is there a better way?
