### ISSUE TITLE
Get an error when try to create a Project.

### ISSUE THREAD

**Issue by carlosrojaso** [Urigo/tortilla#33]
$ tortilla create demoapp -m "How to create a project"

![captura de pantalla 2017-04-27 a la s 4 12 35 p m](https://cloud.githubusercontent.com/assets/6164354/25504685/7dd49950-2b64-11e7-99e3-a7d42d737b1f.png)

**Comment by DAB0mB** [comment]
@carlosrojaso You don't have an SSH defined. For instructions regards SSH see the [this](https://help.github.com/articles/connecting-to-github-with-ssh/) page. For now define SSH, although I can fix it by using HTTP instead, until then I will leave this issue open, tell me if you managed to create a new project. Note that Tortilla is on a super-early alpha stage so you might find more issues, but overall it's super great and once you will get the hang of it it's really awesome. Hopefully in the next days I will release instructional video which introduces Tortilla

**Comment by srtucker22** [comment]
Ok, I defined SSH and GitHub says I've successfully authenticated, but now I'm getting a different error when creating:

```
Cloning into '/var/folders/4z/4y8h5x2j3td1rz5m53_56rmw0000gn/T/tmp-808940SwC14wYpk7W'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/var/folders/4z/4y8h5x2j3td1rz5m53_56rmw0000gn/T/tmp-808940SwC14wYpk7W/package.json'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at overwriteTemplateFile (/Users/simontucker/.config/yarn/global/node_modules/tortilla/src/essentials.js:153:28)
    at Object.createProject [as create] (/Users/simontucker/.config/yarn/global/node_modules/tortilla/src/essentials.js:79:3)
    at Command.<anonymous> (/Users/simontucker/.config/yarn/global/node_modules/tortilla/cli/tortilla:22:16)
    at Command.listener (/Users/simontucker/.config/yarn/global/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/Users/simontucker/.config/yarn/global/node_modules/commander/index.js:615:12)
    at Command.parse (/Users/simontucker/.config/yarn/global/node_modules/commander/index.js:458:21)```

**Comment by srtucker22** [comment]
looks solved now that [`tortilla-skeleton`](https://github.com/Urigo/tortilla-skeleton) is open
